language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.6

matrix:
  include:
    - # GitHub Pages
      rvm: 2.5.3
      env: GH_PAGES=true

before_install:
  - gem update --system
  - bundle update
script : script/cibuild

env:
  - JEKYLL_VERSION=3.7.4

