language: ruby
script : script/cibuild
cache: bundler
sudo: false

before_install: 
  - gem update --system
  - bundle update
rvm:
  - 2.2
  - 2.3
  - 2.4
  - 2.5
env:
  - ""
  - JEKYLL_VERSION=3.6

matrix:
  include:
    - # GitHub Pages
      rvm: 2.4.0
      env: GH_PAGES=true
